'use client';import {useState} from 'react';
export default function MasterDataManager({items,customers,suppliers,readOnly}:{items:any[],customers:any[],suppliers:any[],readOnly:boolean}){const [tab,setTab]=useState<'item'|'customer'|'supplier'>('item');const [editing,setEditing]=useState<any|null>(null);const [msg,setMsg]=useState('');const rows=tab==='item'?items:tab==='customer'?customers:suppliers;
 async function save(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.resource=tab==='item'?'item':'partner';if(b.resource==='partner')b.type=tab==='customer'?'CUSTOMER':'SUPPLIER';if(editing)b.id=editing.id;const r=await fetch('/api/master',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json().catch(()=>({}));setMsg(r.ok?(editing?'Data diperbarui.':'Data ditambahkan.'):(d.message||d.error||'Gagal menyimpan.'));if(r.ok)setTimeout(()=>location.reload(),450)}
 async function del(x:any){if(!confirm(`Hapus ${x.code} - ${x.name}?`))return;const r=await fetch('/api/master',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:tab==='item'?'item':'partner',id:x.id})});const d=await r.json().catch(()=>({}));setMsg(r.ok?'Data dihapus.':(d.message||'Data tidak dapat dihapus.'));if(r.ok)setTimeout(()=>location.reload(),450)}
 function newData(){setEditing({__new:true,code:'',name:'',unit:'PCS'})}
 return <><div className="tabs"><button className={tab==='item'?'tab active':'tab'} onClick={()=>{setTab('item');setEditing(null)}}>Barang</button><button className={tab==='customer'?'tab active':'tab'} onClick={()=>{setTab('customer');setEditing(null)}}>Pelanggan</button><button className={tab==='supplier'?'tab active':'tab'} onClick={()=>{setTab('supplier');setEditing(null)}}>Pemasok</button></div><div className="row" style={{justifyContent:'space-between',margin:'14px 0'}}><div className="muted">{rows.length} data {tab==='item'?'barang':tab==='customer'?'pelanggan':'pemasok'}</div>{!readOnly&&<button className="btn" onClick={newData}>+ Tambah Data</button>}</div>{msg&&<div className="notice" style={{marginBottom:12}}>{msg}</div>}
 <div className="table-wrap"><table className="table"><thead><tr><th>Kode</th><th>Nama</th>{tab==='item'?<><th>HS Code</th><th>Satuan</th><th>Kategori</th></>:<><th>NPWP/Tax ID</th><th>Kontak</th></>}<th>Aksi</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><strong>{x.code}</strong></td><td>{x.name}</td>{tab==='item'?<><td>{x.hsCode||'-'}</td><td>{x.unit}</td><td>{x.category||'-'}</td></>:<><td>{x.taxId||'-'}</td><td>{x.email||x.phone||'-'}</td></>}<td>{readOnly?'-':<div className="row"><button className="btn secondary small" onClick={()=>setEditing(x)}>Edit</button><button className="btn danger small" onClick={()=>del(x)}>Hapus</button></div>}</td></tr>)}</tbody></table></div>
 {editing&&<div className="modal-backdrop"><div className="modal"><div className="row" style={{justifyContent:'space-between'}}><h3>{editing.__new?'Tambah':'Edit'} {tab==='item'?'Barang':tab==='customer'?'Pelanggan':'Pemasok'}</h3><button className="btn secondary" onClick={()=>setEditing(null)}>Tutup</button></div><form className="form" onSubmit={save}><input className="input" name="code" defaultValue={editing.code||''} placeholder="Kode" required/><input className="input" name="name" defaultValue={editing.name||''} placeholder="Nama" required/>{tab==='item'?<><input className="input" name="hsCode" defaultValue={editing.hsCode||''} placeholder="HS Code"/><input className="input" name="unit" defaultValue={editing.unit||'PCS'} placeholder="Satuan"/><select className="input" name="category" defaultValue={editing.category||''}><option value="">Kategori barang...</option><option>BAHAN_BAKU</option><option>BAHAN_PENOLONG</option><option>HASIL_PRODUKSI</option><option>BARANG_MODAL</option><option>SCRAP</option><option>WIP</option><option>LAINNYA</option></select><input className="input" name="customsUnit" defaultValue={editing.customsUnit||''} placeholder="Satuan kepabeanan"/><input className="input" name="countryOfOrigin" defaultValue={editing.countryOfOrigin||''} placeholder="Negara asal"/></>:<><input className="input" name="taxId" defaultValue={editing.taxId||''} placeholder="NPWP / Tax ID"/><textarea className="input" name="address" defaultValue={editing.address||''} placeholder="Alamat"/><input className="input" name="email" defaultValue={editing.email||''} placeholder="Email"/><input className="input" name="phone" defaultValue={editing.phone||''} placeholder="Telepon"/></>}<button className="btn">Simpan</button></form></div></div>}
 </>}
