import {getCurrentUser} from '@/lib/auth';import {prisma} from '@/lib/prisma';
function ro(r:string){return r==='CUSTOMS'||r==='AUDITOR'}
export async function POST(req:Request){const u=await getCurrentUser();if(!u)return Response.json({error:'unauthorized'},{status:401});if(ro(u.role))return Response.json({error:'read_only'},{status:403});const b=await req.json();
  if(b.resource==='item'){const x=await prisma.item.create({data:{companyId:u.companyId,code:String(b.code).trim(),name:String(b.name).trim(),hsCode:b.hsCode||null,unit:b.unit||'PCS',category:b.category||null,customsUnit:b.customsUnit||null,countryOfOrigin:b.countryOfOrigin||null}});await log(u,'CREATE','ITEM',x.id,b);return Response.json({ok:true})}
  if(b.resource==='partner'){const x=await prisma.partner.create({data:{companyId:u.companyId,code:String(b.code).trim(),name:String(b.name).trim(),type:b.type,taxId:b.taxId||null,address:b.address||null,email:b.email||null,phone:b.phone||null}});await log(u,'CREATE','PARTNER',x.id,b);return Response.json({ok:true})}
  return Response.json({error:'bad_resource'},{status:400})}
export async function PATCH(req:Request){const u=await getCurrentUser();if(!u)return Response.json({error:'unauthorized'},{status:401});if(ro(u.role))return Response.json({error:'read_only'},{status:403});const b=await req.json();
  if(b.resource==='item'){const old=await prisma.item.findFirst({where:{id:b.id,companyId:u.companyId}});if(!old)return Response.json({error:'not_found'},{status:404});const x=await prisma.item.update({where:{id:b.id},data:{code:String(b.code).trim(),name:String(b.name).trim(),hsCode:b.hsCode||null,unit:b.unit||'PCS',category:b.category||null,customsUnit:b.customsUnit||null,countryOfOrigin:b.countryOfOrigin||null}});await log(u,'UPDATE','ITEM',x.id,{before:{code:old.code,name:old.name,hsCode:old.hsCode,unit:old.unit,category:old.category},after:{code:x.code,name:x.name,hsCode:x.hsCode,unit:x.unit,category:x.category}});return Response.json({ok:true})}
  if(b.resource==='partner'){const old=await prisma.partner.findFirst({where:{id:b.id,companyId:u.companyId}});if(!old)return Response.json({error:'not_found'},{status:404});const x=await prisma.partner.update({where:{id:b.id},data:{code:String(b.code).trim(),name:String(b.name).trim(),type:b.type,taxId:b.taxId||null,address:b.address||null,email:b.email||null,phone:b.phone||null}});await log(u,'UPDATE','PARTNER',x.id,{before:{code:old.code,name:old.name,type:old.type,taxId:old.taxId},after:{code:x.code,name:x.name,type:x.type,taxId:x.taxId}});return Response.json({ok:true})}
  return Response.json({error:'bad_resource'},{status:400})}
export async function DELETE(req:Request){const u=await getCurrentUser();if(!u)return Response.json({error:'unauthorized'},{status:401});if(ro(u.role))return Response.json({error:'read_only'},{status:403});const b=await req.json();
  if(b.resource==='item'){const x=await prisma.item.findFirst({where:{id:b.id,companyId:u.companyId}});if(!x)return Response.json({error:'not_found'},{status:404});const count=await prisma.transaction.count({where:{companyId:u.companyId,itemId:x.id}});if(count)return Response.json({error:'item_in_use',message:`Barang dipakai oleh ${count} transaksi. Hapus/koreksi transaksi terlebih dahulu.`},{status:409});await prisma.stockOpname.deleteMany({where:{companyId:u.companyId,itemId:x.id}});await prisma.item.delete({where:{id:x.id}});await log(u,'DELETE','ITEM',x.id,{code:x.code,name:x.name,hsCode:x.hsCode,unit:x.unit,category:x.category});return Response.json({ok:true})}
  if(b.resource==='partner'){const x=await prisma.partner.findFirst({where:{id:b.id,companyId:u.companyId}});if(!x)return Response.json({error:'not_found'},{status:404});await prisma.partner.delete({where:{id:x.id}});await log(u,'DELETE','PARTNER',x.id,{code:x.code,name:x.name,type:x.type,taxId:x.taxId});return Response.json({ok:true})}
  return Response.json({error:'bad_resource'},{status:400})}
async function log(u:any,action:string,entity:string,id:string,metadata:any){await prisma.auditLog.create({data:{companyId:u.companyId,userId:u.id,action,entity,entityId:id,metadata}})}
